import Link from "next/link"; import { CodeBlock } from "@/components/code-block"; import { Container } from "@/components/container"; import { comparison, faqs, languages, mcpTools } from "@/data/marketing"; import { siteConfig as site } from "@/config/site";
export const ProofStrip=()=> <section className="proof-strip"><Container>{["Local analysis","Python · JS · TS stable","7 experimental adapters","CLI","MCP","MIT license"].map(x=><span key={x}>{x}</span>)}</Container></section>;
export function InstallWorkflow(){const steps: [string,string,string][]=[["01","Install",site.installCommand],["02","Build",site.commands.build],["03","Investigate","tokenoptipy hotspots\ntokenoptipy explain NODE_ID\ntokenoptipy path SOURCE TARGET"]];return <Section id="how-it-works" eyebrow="Install → Build → Investigate" title="From repository to evidence in three steps."><div className="workflow">{steps.map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><CodeBlock code={x[2]}/></article>)}</div><pre className="output-tree">tokenoptipy-out/{"\n"}├── graph.html{"\n"}├── graph.json{"\n"}└── TOKEN_REPORT.md</pre></Section>}
export function TokenSources(){return <Section eyebrow="Token-bearing content" title="Where the tokens come from."><div className="source-flow">{["System prompts","Conversation history","Retrieved content","Variables & schemas","Few-shot examples","Model call"].map((x,i)=><div key={x} data-final={i===5}><span>0{i+1}</span>{x}</div>)}</div><p className="section-note">TokenOptiPy connects these sources across files and functions. Dynamic values remain estimates until runtime.</p></Section>}
export function HotspotInvestigation(){const parts=[["Product catalog",8500],["Conversation history",2900],["System prompt",320],["Other static and dynamic values",750]] as const;return <Section eyebrow="Illustrative example" title="Investigate a hotspot by contribution."><div className="hotspot"><div><span>Analyzed call</span><strong>answer_customer</strong></div><div><span>Estimated static input</span><strong>12,470 tokens</strong></div><div className="stacked" aria-label="Estimated token contribution chart">{parts.map(([n,v])=><span key={n} style={{width:`${v/12470*100}%`}} title={`${n}: ${v}`}/>)}</div><ul>{parts.map(([n,v])=><li key={n}><span>{n}</span><b>{v.toLocaleString()}</b></li>)}</ul><p>TokenOptiPy identifies optimization opportunities. The effect on cost and model quality must be validated with representative evaluation cases.</p></div></Section>}
export function McpWorkflow(){return <Section id="mcp" eyebrow="CLI + local MCP" title="Query the TokenGraph from your development workflow."><div className="terminal-pipeline">{[...mcpTools.slice(0,2),"edit prompt",...mcpTools.slice(2)].map((x,i)=><span key={x}>{i>0&&<i>→</i>}<code>{x}</code></span>)}</div><p className="section-note">The stdio MCP server supports compatible local clients. Confirmed setup includes Codex, Claude, GitHub Copilot and VS Code, Cursor, Windsurf, Cline, Roo Code, Continue, and generic MCP clients. Traces exclude prompt bodies and sensitive tool arguments.</p></Section>}
export function LanguageSupport(){return <Section eyebrow="Analysis levels" title="Stable parsers. Explicit experimental boundaries."><div className="table-wrap"><table><thead><tr>{["Language","Parser strategy","Import analysis","Prompt detection","Model-call detection","Status"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{languages.map(x=><tr key={x.language}><td>{x.language}</td><td>{x.parser}</td><td>{x.imports}</td><td>{x.prompts}</td><td>{x.calls}</td><td><span className={`status ${x.status.toLowerCase()}`}>{x.status}</span></td></tr>)}</tbody></table></div><p className="section-note">Experimental adapters use conservative structural evidence. They may miss dynamic flows, reflection, framework-specific patterns, or complex macros.</p></Section>}
export function PrivacyArchitecture(){return <Section id="security" eyebrow="Privacy & security" title="Your code stays on your machine."><div className="architecture">{["Repository","Local scanner","TokenGraph files","CLI / Browser / MCP"].map((x,i)=><span key={x}>{i>0&&<i>→</i>}<b>{x}</b></span>)}</div><div className="privacy-copy"><p>Analysis is local by default. Source code, imports, compilers, package scripts, and project dependencies are not executed. No mandatory remote API or OpenAI key is required.</p><p>Likely secrets are redacted from previews. Reports may still contain file paths, names, hashes, signatures, and metadata—review them before publishing.</p></div></Section>}
export function ComparisonTable(){return <Section eyebrow="Different evidence" title="Static token-flow analysis complements runtime observability."><div className="table-wrap"><table><thead><tr>{["Criterion","TokenOptiPy","Manual inspection","Token counters","Runtime observability"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{comparison.map(r=><tr key={r[0]}>{r.map((x,i)=><td key={`${r[0]}-${i}`} className={i===1?"accent":""}>{x}</td>)}</tr>)}</tbody></table></div><p className="section-note">Runtime tools observe actual requests. TokenOptiPy provides local pre-execution evidence; use both when runtime accuracy matters.</p></Section>}
export function Faq(){return <Section eyebrow="FAQ" title="What the static analysis can—and cannot—tell you."><div className="faq">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></Section>}
export function FinalCta(){return <section className="final-cta"><Container><p className="eyebrow">TokenOptiPy {site.version}</p><h2>Build your first local TokenGraph.</h2><CodeBlock code={`${site.installCommand}\n${site.commands.build}`}/><div><Link href={site.docs.quickstart} className="button-primary">Get started</Link><a href={site.productRepositoryUrl} className="button-secondary">View source</a></div></Container></section>}
export function Section({id,eyebrow,title,children}:{id?:string;eyebrow:string;title:string;children:React.ReactNode}){return <section id={id} className="marketing-section"><Container><header><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></header>{children}</Container></section>}
