"use client";
import { useMemo, useState } from "react";
import { demoEdges, demoNodes, type DemoNodeType } from "@/data/demo-graph";

const colors: Record<DemoNodeType,string>={file:"#94a3b8",prompt:"#818cf8",variable:"#22d3ee",context:"#38bdf8",function:"#a78bfa",model_call:"#fb7185",finding:"#f59e0b"};
export function TokenGraphShowcase({ compact=false }: { compact?: boolean }) {
 const [selected,setSelected]=useState("model"),[query,setQuery]=useState(""),[type,setType]=useState<DemoNodeType|"all">("all"),[hotspots,setHotspots]=useState(false);
 const visible=useMemo(()=>demoNodes.filter(n=>(type==="all"||n.type===type)&&(!hotspots||n.tokens>=2500)&&n.label.toLowerCase().includes(query.toLowerCase())),[query,type,hotspots]);
 const active=demoNodes.find(n=>n.id===selected)??demoNodes[4]!; const ids=new Set(visible.map(n=>n.id));
 const incoming=demoEdges.filter(e=>e.target===active.id),outgoing=demoEdges.filter(e=>e.source===active.id);
 return <div className={`graph-shell ${compact?"graph-compact":""}`}>
  <div className="graph-toolbar"><span className="demo-label">Demonstration data · 60 nodes</span><input aria-label="Search demo graph" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search nodes…"/><select aria-label="Filter node type" value={type} onChange={e=>setType(e.target.value as DemoNodeType|"all")}><option value="all">All node types</option>{Object.keys(colors).map(t=><option key={t}>{t}</option>)}</select><label><input type="checkbox" checked={hotspots} onChange={e=>setHotspots(e.target.checked)}/> Hotspots</label><button onClick={()=>{setQuery("");setType("all");setHotspots(false);setSelected("model")}}>Reset view</button><button onClick={()=>setSelected("model")}>Fit graph</button></div>
  <div className="graph-layout"><div className="graph-canvas"><div className="site-grid absolute inset-0"/><svg viewBox="0 0 1000 600" aria-label="Interactive demonstration TokenGraph">{demoEdges.filter(e=>ids.has(e.source)&&ids.has(e.target)).map((e,i)=>{const a=demoNodes.find(n=>n.id===e.source)!,b=demoNodes.find(n=>n.id===e.target)!;return <line key={i} x1={a.x*10} y1={a.y*6} x2={b.x*10} y2={b.y*6} className={e.highlighted?"graph-edge graph-edge-active":"graph-edge"}/>})}{visible.map(n=><g key={n.id} role="button" tabIndex={0} aria-label={`${n.label}, ${n.type}, ${n.tokens} estimated tokens`} onClick={()=>setSelected(n.id)} onFocus={()=>setSelected(n.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")setSelected(n.id)}} className="graph-dot" data-selected={n.id===active.id} transform={`translate(${n.x*10} ${n.y*6})`}><circle r={n.type==="model_call"?14:Math.max(5,Math.min(11,5+n.tokens/1800))} fill={colors[n.type]}/>{(n.id===active.id||n.id==="support"||n.id==="system"||n.id==="history"||n.id==="answer")&&<text x="18" y="4">{n.label}</text>}</g>)}</svg></div>
  {!compact&&<aside className="graph-inspector"><p className="eyebrow">Selected node</p><h3>{active.label}</h3><dl><div><dt>Node type</dt><dd style={{color:colors[active.type]}}>{active.type}</dd></div><div><dt>Estimated static tokens</dt><dd>{active.tokens.toLocaleString()}</dd></div><div><dt>Source</dt><dd>{active.source}</dd></div><div><dt>Incoming / outgoing</dt><dd>{incoming.length} / {outgoing.length}</dd></div></dl><div><h4>Associated finding</h4><p>{active.finding??"No finding attached to this demonstration node."}</p></div><div><h4>Relationships</h4><p>{[...incoming,...outgoing].slice(0,4).map(e=>e.relation).join(" · ")||"None"}</p></div></aside>}</div>
 </div>
}
