import type { Metadata } from "next";
import Link from "next/link";
import { CodeBlock } from "@/components/code-block";
import { Container } from "@/components/container";
import { HeroGraph } from "@/components/hero-graph";
import { ArrowRightIcon, BracesIcon, CheckIcon, ExternalIcon, GithubIcon, ShieldIcon, TerminalIcon } from "@/components/icons";
import { SectionHeading } from "@/components/section-heading";
import { TokenGraphDemo } from "@/components/token-graph-demo";
import { AnimatedCounter } from "@/components/motion/animated-counter";
import { Reveal } from "@/components/motion/reveal";
import { siteConfig as site } from "@/config/site";

export const metadata: Metadata = {
  title: "See where every token goes",
  description: site.description,
  alternates: { canonical: "/" },
};

const problems = [
  "Prompts that grow past their useful core",
  "Context injected from several files and variables",
  "Conversation history with no visible upper bound",
  "Duplicated instructions, schemas, and examples",
  "Unclear paths between source content and model calls",
  "Optimizations that save tokens but may change behavior",
];

const steps = [
  { number: "01", title: "Scan locally", text: "Analyze supported Python, prompt, text, structured resource, and Jinja files without executing the project." },
  { number: "02", title: "Build the TokenGraph", text: "Connect files, prompts, variables, contexts, functions, model calls, findings, and token flows." },
  { number: "03", title: "Find hotspots", text: "Rank token-heavy prompts and model calls, then inspect paths, dynamic inputs, and duplicated content." },
  { number: "04", title: "Validate improvements", text: "Compare prompt candidates and check required terms, placeholders, numbers, negations, and structure." },
];

const agents = ["OpenAI Codex", "Claude Code", "Claude Desktop", "GitHub Copilot", "VS Code", "Cursor", "Windsurf", "Cline", "Roo Code", "Continue", "Generic MCP stdio"];
const tools = ["inspect_workspace", "analyze_prompt_file", "validate_prompt_change", "query_token_flow", "get_prompt_flow", "build_graph_report", "get_traceability"];

export default function HomePage() {
  return (
    <>
      <section className="relative overflow-hidden border-b border-[var(--border)] py-20 sm:py-28 lg:py-32">
        <div className="site-grid absolute inset-0" />
        <div className="absolute left-1/2 top-0 h-[520px] w-[900px] -translate-x-1/2 rounded-full bg-indigo-500/10 blur-3xl" />
        <Container className="relative grid items-center gap-14 lg:grid-cols-[1.02fr_.98fr]">
          <div className="hero-sequence">
            <div className="inline-flex items-center gap-2 rounded-full border border-indigo-500/20 bg-indigo-500/8 px-3 py-1.5 text-xs font-semibold text-indigo-600"><span className="size-1.5 rounded-full bg-emerald-500" />Open source · Local-first · MCP compatible</div>
            <h1 className="mt-7 max-w-4xl text-balance text-5xl font-semibold tracking-[-0.055em] text-[var(--text-strong)] sm:text-6xl lg:text-7xl">See where every <span className="gradient-text">token goes.</span></h1>
            <p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--text-muted)] sm:text-xl">TokenOptiPy builds a local graph of prompts, context, variables, functions and model calls so you can find token hotspots and validate safer optimizations.</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={site.docs.quickstart} className="button-primary">Build your first TokenGraph<ArrowRightIcon className="size-4" /></Link><a href={site.productRepositoryUrl} aria-label="Open the TokenOptiPy product repository on GitHub" className="button-secondary" target="_blank" rel="noopener noreferrer"><GithubIcon className="size-4" />View on GitHub</a></div>
            <div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-[var(--text-dim)]"><span>Python 3.10+</span><span>TokenOptiPy {site.version}</span><span>No mandatory API key</span></div>
          </div>
          <div className="hero-graph-entry"><HeroGraph /></div>
        </Container>
      </section>

      <section id="product" className="py-20 sm:py-28"><Container><SectionHeading eyebrow="The problem" title="Your prompt is only part of the token bill."><p>Model calls often combine content from places that are difficult to inspect together. Static evidence helps teams understand what may reach a model before changing prompts blindly.</p></SectionHeading><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{problems.map((problem) => <div key={problem} className="feature-card flex gap-3"><span className="mt-1 flex size-7 shrink-0 items-center justify-center rounded-lg bg-amber-500/10 text-amber-600">!</span><p className="leading-7 text-[var(--text-muted)]">{problem}</p></div>)}</div></Container></section>

      <section className="border-y border-[var(--border)] bg-[var(--surface-muted)]/40 py-20 sm:py-28"><Container><SectionHeading eyebrow="How it works" title="Inspect evidence, then optimize carefully."><p>TokenOptiPy provides local static-analysis evidence. It does not claim to know every runtime value or guarantee model quality.</p></SectionHeading><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{steps.map((step) => <div key={step.number} className="feature-card"><span className="font-mono text-xs text-indigo-500">{step.number}</span><h3 className="mt-6 text-lg font-semibold text-[var(--text-strong)]">{step.title}</h3><p className="mt-3 text-sm leading-7 text-[var(--text-muted)]">{step.text}</p></div>)}</div><div className="mt-8 rounded-2xl border border-amber-500/25 bg-amber-500/8 p-5 text-sm leading-7 text-[var(--text-muted)]"><strong className="text-[var(--text-strong)]">Important:</strong> Token savings are estimates. Quality must be validated with representative evaluation cases.</div></Container></section>

      <section className="py-20 sm:py-28"><Container><SectionHeading eyebrow="Interactive TokenGraph" title="Follow content from source to model call."><p>Focus any node to inspect its type, estimated static tokens, and incoming or outgoing relations. The visualization below uses demonstration data only.</p></SectionHeading><Reveal className="mt-12"><TokenGraphDemo /></Reveal></Container></section>

      <section className="border-y border-[var(--border)] bg-[var(--surface-muted)]/40 py-20 sm:py-28"><Container><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><SectionHeading eyebrow="Illustrative workflow" title="Turn a large call into an explainable investigation."><p>This example shows how a team might isolate the largest static sources before making an application-specific change.</p><p className="mt-5 text-sm">Actual savings depend on the application and must be evaluated for quality.</p></SectionHeading><div className="panel p-6 sm:p-8"><p className="font-mono text-xs uppercase tracking-[.14em] text-[var(--text-dim)]">Analyzed call</p><h3 className="mt-2 text-2xl font-semibold text-[var(--text-strong)]">answer_customer</h3><div className="mt-7 grid gap-4 sm:grid-cols-3"><Metric label="Estimated before" value="12,470" suffix="tokens" /><Metric label="Estimated after" value="2,180" suffix="tokens" /><Metric label="Potential reduction" value="82.5%" accent /></div><div className="mt-8 border-t border-[var(--border)] pt-6"><p className="text-sm font-semibold text-[var(--text-strong)]">Main detected sources</p><div className="mt-4 space-y-3"><SourceRow label="full product catalog" tokens="8,500" width="100%" /><SourceRow label="conversation history" tokens="2,900" width="34%" /><SourceRow label="system prompt" tokens="320" width="8%" /></div></div></div></div></Container></section>

      <section className="py-20 sm:py-28"><Container><div className="grid gap-12 lg:grid-cols-2 lg:items-start"><SectionHeading eyebrow="CLI" title="Build and query the graph from your terminal."><p>The Python CLI produces a self-contained HTML report, a machine-readable graph, and a Markdown report.</p><div className="mt-7 flex flex-wrap gap-3"><Link href={site.docs.cli} className="button-secondary">Read CLI docs<ArrowRightIcon className="size-4" /></Link></div></SectionHeading><div className="space-y-4"><CodeBlock label="Install" code={site.installCommand} /><CodeBlock label="Build" code={site.commands.build} /><CodeBlock label="Inspect hotspots" code={site.commands.hotspots} /></div></div></Container></section>

      <section className="border-y border-[var(--border)] bg-[var(--surface-muted)]/40 py-20 sm:py-28"><Container><div className="grid gap-12 lg:grid-cols-[1fr_1fr]"><div><SectionHeading eyebrow="MCP server" title="Give compatible agents local token-flow tools."><p>TokenOptiPy exposes a standard MCP server over stdio. Exact capabilities depend on each client&apos;s MCP support, and configuration or instruction files may be required.</p></SectionHeading><div className="mt-8 flex flex-wrap gap-2">{agents.map((agent) => <span key={agent} className="rounded-full border border-[var(--border)] bg-[var(--surface)] px-3 py-1.5 text-xs text-[var(--text-muted)]">{agent}</span>)}</div><div className="mt-7"><Link href={site.docs.mcp} className="button-secondary">MCP setup and limits<ArrowRightIcon className="size-4" /></Link></div></div><div className="panel overflow-hidden"><div className="border-b border-[var(--border)] px-5 py-4"><p className="font-mono text-xs text-indigo-500">Suggested workflow</p></div><div className="p-5"><div className="flex flex-wrap items-center gap-2 font-mono text-xs">{["inspect_workspace", "get_prompt_flow", "edit prompt", "validate_prompt_change", "build_graph_report"].map((item, index, arr) => <span key={item} className="contents"><span className="rounded-lg border border-[var(--border)] bg-[var(--surface-muted)] px-3 py-2 text-[var(--text)]">{item}</span>{index < arr.length - 1 && <ArrowRightIcon className="size-4 text-indigo-500" />}</span>)}</div><div className="mt-8 grid gap-2 sm:grid-cols-2">{tools.map((tool) => <div key={tool} className="rounded-lg border border-[var(--border)] px-3 py-2 font-mono text-xs text-[var(--text-muted)]">{tool}</div>)}</div></div></div></div></Container></section>

      <section className="py-20 sm:py-28"><Container><div className="grid gap-12 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div className="panel relative min-h-[420px] overflow-hidden p-6"><div className="site-grid absolute inset-0" /><div className="relative rounded-xl border border-[var(--border)] bg-[var(--surface)] shadow-2xl"><div className="flex items-center gap-2 border-b border-[var(--border)] px-4 py-3"><span className="size-2.5 rounded-full bg-red-400" /><span className="size-2.5 rounded-full bg-amber-400" /><span className="size-2.5 rounded-full bg-emerald-400" /><span className="ml-3 text-xs text-[var(--text-dim)]">VS Code · TokenOptiPy</span></div><div className="grid grid-cols-[52px_1fr] min-h-[315px]"><div className="border-r border-[var(--border)] p-3 text-center text-indigo-500"><BracesIcon className="mx-auto" /></div><div className="p-5"><p className="font-mono text-xs text-[var(--text-dim)]">TOKENOPTIPY MCP TRACEABILITY</p><div className="mt-5 rounded-xl border border-[var(--border)] bg-[var(--surface-muted)] p-4"><p className="text-sm font-medium text-[var(--text-strong)]">✓ get_prompt_flow · 84ms</p><p className="mt-2 font-mono text-xs text-[var(--text-muted)]">Trace 7d2c… · prompt bodies excluded</p></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-[var(--border)] p-4"><p className="text-xs text-[var(--text-dim)]">Hotspot</p><p className="mt-2 text-xl font-semibold text-[var(--text-strong)]">12.4k</p></div><div className="rounded-xl border border-[var(--border)] p-4"><p className="text-xs text-[var(--text-dim)]">Graph</p><p className="mt-2 text-sm font-semibold text-indigo-500">Open graph.html</p></div></div></div></div></div></div><div><SectionHeading eyebrow="VS Code extension" title={site.extensionName}><p>Register the local MCP server, watch safe trace metadata in the status bar, build and open <code>graph.html</code>, configure MCP clients, and inspect prompt flows from the editor.</p></SectionHeading><ul className="mt-7 grid gap-3 text-sm text-[var(--text-muted)] sm:grid-cols-2">{["MCP server registration", "Status-bar traceability", "Build and open TokenGraph", "Configure MCP clients", "Workspace graph generation", "Prompt-flow inspection"].map((item) => <li key={item} className="flex gap-2"><CheckIcon className="mt-0.5 size-4 shrink-0 text-emerald-500" />{item}</li>)}</ul><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={site.marketplaceUrl} aria-label="Install TokenOptiPy from the Visual Studio Marketplace" className="button-primary" target="_blank" rel="noopener noreferrer">Install from Visual Studio Marketplace<ExternalIcon className="size-4" /></a><Link href={site.docs.vscode} className="button-secondary">Extension docs</Link></div><p className="mt-4 font-mono text-xs text-[var(--text-dim)]">{site.extensionId}</p></div></div></Container></section>

      <section className="relative overflow-hidden border-y border-[var(--border)] py-20 sm:py-28"><div className="absolute inset-0 bg-indigo-500/[.035]" /><Container className="relative"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Privacy" title="Local by default. Private by design."><p>TokenOptiPy performs analysis locally and does not require source code uploads, a remote API, or an OpenAI key.</p><div className="mt-7"><Link href="/privacy" className="button-secondary">Read the privacy model<ShieldIcon className="size-4" /></Link></div></SectionHeading><div className="grid gap-4 sm:grid-cols-2">{["Analysis runs locally", "No mandatory source-code upload", "No OpenAI API key required", "No remote API required", "Full prompts excluded from MCP traces", "Tool arguments excluded from traces", "Likely secrets redacted from previews", "Self-contained local graph.html"].map((item) => <div key={item} className="feature-card flex items-start gap-3"><ShieldIcon className="mt-0.5 size-5 shrink-0 text-indigo-500" /><span className="text-sm leading-6 text-[var(--text-muted)]">{item}</span></div>)}</div></div><div className="mt-10 rounded-2xl border border-[var(--border)] bg-[var(--surface-elevated)] p-5 text-sm leading-7 text-[var(--text-muted)]">Generated reports can contain file paths or names, hashes, node metadata, signatures, and redacted previews. Review reports before sharing them publicly.</div></Container></section>

      <section className="py-20 sm:py-28"><Container><div className="panel relative overflow-hidden px-6 py-14 text-center sm:px-12"><div className="site-grid absolute inset-0" /><div className="absolute left-1/2 top-0 h-64 w-2/3 -translate-x-1/2 rounded-full bg-indigo-500/15 blur-3xl" /><div className="relative"><TerminalIcon className="mx-auto size-9 text-indigo-500" /><h2 className="mt-5 text-balance text-3xl font-semibold tracking-[-0.04em] text-[var(--text-strong)] sm:text-5xl">Build your first TokenGraph.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[var(--text-muted)]">Install TokenOptiPy from GitHub, scan a Python LLM project locally, and open the generated interactive report.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href={site.docs.quickstart} className="button-primary">Get started<ArrowRightIcon className="size-4" /></Link><a href={site.productRepositoryUrl} aria-label="Open the TokenOptiPy product repository on GitHub" target="_blank" rel="noopener noreferrer" className="button-secondary"><GithubIcon className="size-4" />View source</a></div></div></div></Container></section>
    </>
  );
}

function Metric({ label, value, suffix, accent = false }: { label: string; value: string; suffix?: string; accent?: boolean }) { const numeric=Number(value.replace(/[,%%]/g,"")); return <div className="rounded-xl bg-[var(--surface-muted)] p-4"><p className="text-xs text-[var(--text-dim)]">{label}</p><p className={`mt-2 text-2xl font-semibold ${accent ? "text-emerald-500" : "text-[var(--text-strong)]"}`}><AnimatedCounter value={numeric} decimals={value.includes(".") ? 1 : 0} suffix={value.includes("%") ? "%" : ""} /></p>{suffix && <p className="mt-1 text-xs text-[var(--text-dim)]">{suffix}</p>}</div>; }
function SourceRow({ label, tokens, width }: { label: string; tokens: string; width: string }) { return <div><div className="flex items-center justify-between gap-4 text-sm"><span className="text-[var(--text-muted)]">{label}</span><span className="font-mono text-[var(--text-strong)]">{tokens}</span></div><div className="mt-2 h-1.5 rounded-full bg-[var(--surface-muted)]"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-violet-500" style={{ width }} /></div></div>; }
